import fs from "node:fs";
import path from "node:path";
import { getEpisode, parseEpisodeNumber, WORKSPACE_ROOT } from "./helpers.js";

const SCENES_DIR = path.join(
  WORKSPACE_ROOT,
  "artifacts/biominute-reels/src/components/video/video_scenes",
);
const CONFIG_PATH = path.join(
  WORKSPACE_ROOT,
  "artifacts/biominute-reels/src/lib/video/config.ts",
);

const DEFAULT_DURATIONS = {
  0: 4500,
  1: 6500,
  2: 7000,
  3: 6000,
  4: 6500,
  5: 5000,
};

export function prepareEpisodeScenes(epNumber: number, title: string): void {
  for (let index = 0; index <= 4; index++) {
    const archived = path.join(SCENES_DIR, `ep${epNumber}_Scene${index}.tsx`);
    const active = path.join(SCENES_DIR, `Scene${index}.tsx`);
    if (!fs.existsSync(archived)) {
      throw new Error(
        `Missing archived scene for EP${epNumber}: ${path.basename(archived)}. ` +
          "This episode cannot be rendered safely until its source scenes are archived.",
      );
    }
    fs.copyFileSync(archived, active);
  }

  const durationLines = Object.entries(DEFAULT_DURATIONS)
    .map(([index, duration]) => `  ${index}: ${duration}, // Scene ${index}`)
    .join("\n");
  fs.writeFileSync(
    CONFIG_PATH,
    `// BioMinute Reels: generated by the safe production pipeline.
export const VIDEO_WIDTH = 1080;
export const VIDEO_HEIGHT = 1920;
export const VIDEO_ASPECT_RATIO = VIDEO_WIDTH / VIDEO_HEIGHT;
export const SAFE_ZONE_PADDING = 0.08;
export const SAFE_ZONE_PX = VIDEO_WIDTH * SAFE_ZONE_PADDING;
export const BOTTOM_SAFE_ZONE_RATIO = 0.30;
export const BOTTOM_SAFE_ZONE_PX = VIDEO_HEIGHT * BOTTOM_SAFE_ZONE_RATIO;
export const CANVAS_STYLE = { width: VIDEO_WIDTH, height: VIDEO_HEIGHT } as const;
// EP ${epNumber} — "${title.replaceAll('"', '\\"')}"
export const SCENE_DURATIONS = {
${durationLines}
} as const;
`,
  );
}

async function main() {
  const epNumber = parseEpisodeNumber(process.argv[2]);
  const episode = await getEpisode(epNumber);
  prepareEpisodeScenes(epNumber, episode.hookTitle);
  console.log(`PREPARE PASS: active scenes now point to EP${epNumber}.`);
}

main().catch((error) => {
  console.error(`PREPARE FAIL: ${error instanceof Error ? error.message : error}`);
  process.exit(1);
});