// BioMinute Reels: generated by the safe production pipeline.
export const VIDEO_WIDTH = 1080;
export const VIDEO_HEIGHT = 1920;
export const VIDEO_ASPECT_RATIO = VIDEO_WIDTH / VIDEO_HEIGHT;
export const SAFE_ZONE_PADDING = 0.08;
export const SAFE_ZONE_PX = VIDEO_WIDTH * SAFE_ZONE_PADDING;
export const BOTTOM_SAFE_ZONE_RATIO = 0.30;
export const BOTTOM_SAFE_ZONE_PX = VIDEO_HEIGHT * BOTTOM_SAFE_ZONE_RATIO;
export const CANVAS_STYLE = { width: VIDEO_WIDTH, height: VIDEO_HEIGHT } as const;
// EP 90 — "Does Drinking Warm Milk Before Bed Help You Sleep?"
export const SCENE_DURATIONS = {
  0: 4500, // Scene 0
  1: 6500, // Scene 1
  2: 7000, // Scene 2
  3: 6000, // Scene 3
  4: 6500, // Scene 4
  5: 5000, // Scene 5
} as const;
